apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: mini-ecom
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: mini-ecom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo "waiting for postgres"; sleep 2; done;']
      containers:
        - name: user-service
          image: maheshde791/user-service:2.4   # your pushed DockerHub image
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres:5432/usersdb"
          readinessProbe:
            httpGet:
              path: /docs   # FastAPI exposes docs without auth
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
